server:
  port: 8080
  address: 0.0.0.0

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio
      database: portfolio
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  mail:
    host: smtp.ionos.fr
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    com.Portbil.portfolio_backend: DEBUG
    com.Portbil.portfolio_backend.config: DEBUG

openweathermap:
  api-key: ${OPENWEATHERMAP_API_KEY}
  base-url: ${OPENWEATHERMAP_BASE_URL:https://api.openweathermap.org/data/2.5/weather}

app:
  developer:
    id: ${APP_DEVELOPER_ID}
  image:
    go-api-url: ${GO_API_URL:http://localhost:7000/server-image}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://192.168.1.184:5173,https://localhost:5173,https://192.168.1.184:5173}