services:
  # Frontend (React/Vite)
  frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:8080  # Ajoute cette ligne pour le frontend

  # Backend Spring Boot
  backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - APP_DEVELOPER_ID=${APP_DEVELOPER_ID}
    depends_on:
      - mongodb

  # Serveur d'images Go
  image-server:
    build:
      context: ./image-server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./image-server/public:/app/public
      - ./image-server/models:/app/models

  # MongoDB pour le backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: