# Utiliser une image Node.js légère comme base pour le build
FROM node:20-alpine AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et yarn.lock
COPY package.json yarn.lock ./

# Installer les dépendances avec Yarn
RUN yarn install --frozen-lockfile

# Copier tout le code source
COPY . .

# Construire l'application en mode production
RUN yarn build:prod

# Utiliser une image légère pour servir l'application (Nginx)
FROM nginx:alpine

# Copier les fichiers de build dans le répertoire par défaut de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port 80 (par défaut pour Nginx)
EXPOSE 80

# Commande par défaut pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]